import type { ptBR } from './ptBR';
type MessageKey = keyof typeof ptBR;
export const enUS = {
  'app.brand':'Hero Forge','app.tagline':'Memorable characters. Ready before the first initiative.','nav.presets':'Ready-made characters','nav.characters':'My characters','nav.language':'Language',
  'home.eyebrow':'ONE-SHOT CHARACTER TOOL','home.title':'Your next legend starts now.','home.create':'Create character','home.choosePreset':'Choose a ready-made character','home.auto':'Automatic calculations','home.local':'Saved on this device','home.pdf':'Print-ready PDF','home.quick':'QUICK CREATION','home.quickTitle':'Ready to play in minutes','home.quickBody':'Choose a level 5 archetype, give them a name, and adjust only what you want.','home.quickAction':'Start quick creation →','home.available':'10 archetypes available',
  'common.level':'Level','common.remove':'Remove','common.add':'Add','common.edit':'Edit','common.duplicate':'Duplicate','common.delete':'Delete','common.back':'← Back','common.continue':'Continue →','common.save':'Save character','common.downloadPdf':'Download PDF','common.cancel':'Cancel','common.yes':'Yes','common.no':'No','common.auto':'Auto','common.custom':'Custom',
  'steps.identity':'Identity','steps.classSpecies':'Class & species','steps.abilities':'Abilities','steps.skills':'Skills','steps.combat':'Combat & items','steps.spells':'Spells & notes','steps.portrait':'Portrait','steps.review':'Review',
  'editor.new':'New adventurer','editor.creation':'CHARACTER CREATION','editor.step':'STEP {current} OF {total}','form.characterName':'Character name','form.characterPlaceholder':'What is your hero known as?','form.playerName':'Player name','form.required':'Required field','form.class':'Class','form.subclass':'Subclass / path','form.subclassPlaceholder':'Choose according to your table','form.species':'Species','form.armorClass':'Armor class','form.hp':'HP','form.hpAverage':'Automatic average','form.hpManual':'Manual value','form.manualHp':'Manual HP','form.notes':'Notes',
  'pointBuy.rules':'Rules','pointBuy.used':'Used','pointBuy.available':'Available','pointBuy.remaining':'Remaining','pointBuy.final':'Final abilities','pointBuy.finalHelp':'Include species, background, feat, and ASI bonuses here. These values do not affect Point Buy.','validation.pointBuy':'Invalid configuration: adjust purchased abilities to the point limit.','validation.total':'Invalid point total.','validation.integerLimits':'Limits must be integers.','validation.range':'Minimum cannot exceed maximum.','validation.level':'Level limit must be between 1 and 20.','validation.cost':'Invalid cost for ability {score}.',
  'custom.total':'Total points','custom.minimum':'Minimum ability','custom.maximum':'Maximum ability','custom.levelLimit':'Level limit','custom.costTable':'Cost table',
  'attack.title':'Attacks','attack.name':'Name','attack.damageDie':'Damage','attack.ability':'Ability','attack.proficient':'Proficient','attack.attackBonus':'Attack bonus','attack.damageBonus':'Damage bonus','attack.new':'New weapon','attack.add':'Add attack','equipment.title':'Equipment','equipment.new':'New item','spell.title':'Spells','spell.name':'Name','spell.level':'Level','spell.new':'New spell','spell.add':'Add spell','skill.expertise':'Expertise',
  'portrait.title':'Character portrait','portrait.help':'PNG, JPG, or WEBP. The image will also appear in the PDF.','portrait.choose':'Choose image','sheet.title':'ADVENTURER SHEET','sheet.unnamed':'Unnamed hero','sheet.hp':'HP','sheet.ac':'AC','sheet.initiative':'INIT.','sheet.proficiency':'PROF.','sheet.saves':'Saving Throws','sheet.skills':'Skills','sheet.attacks':'Attacks','sheet.equipment':'Equipment','sheet.spells':'Spells','sheet.notes':'Notes','sheet.features':'Features','sheet.attack':'attack','sheet.damage':'damage',
  'library.eyebrow':'LOCAL LIBRARY','library.help':'Your heroes are saved only on this device.','library.new':'New character','library.empty':'Your party is still empty','library.emptyHelp':'Create a hero or start with a ready-made archetype.','library.viewPresets':'View ready-made characters','library.confirmDelete':'Delete this character?','library.copy':'(copy)','preset.eyebrow':'QUICK CREATION','preset.title':'Choose your archetype','preset.help':'All start at level 5 and can be fully customized.','preset.use':'Use and customize','preset.ready':'A level 5 {role}, ready to enter the scene.','preset.featureArchetype':'Level 5 archetype','preset.featureResources':'Class attacks and features','preset.notes':'Adjust subclass choices and features according to the books allowed at your table.',
  'role.tank':'tank fighter','role.barbarian':'strength barbarian','role.rogue':'stealth rogue','role.wizard':'offensive wizard','role.cleric':'support cleric','role.paladin':'guardian paladin','role.ranger':'scout ranger','role.bard':'versatile bard','role.monk':'agile monk','role.warlock':'occult warlock',
  'ability.strength':'Strength','ability.dexterity':'Dexterity','ability.constitution':'Constitution','ability.intelligence':'Intelligence','ability.wisdom':'Wisdom','ability.charisma':'Charisma',
  'class.fighter':'Fighter','class.barbarian':'Barbarian','class.rogue':'Rogue','class.wizard':'Wizard','class.cleric':'Cleric','class.paladin':'Paladin','class.ranger':'Ranger','class.bard':'Bard','class.monk':'Monk','class.warlock':'Warlock',
  'species.human':'Human','species.elf':'Elf','species.dwarf':'Dwarf','species.halfling':'Halfling','species.tiefling':'Tiefling','species.dragonborn':'Dragonborn',
  'skill.acrobatics':'Acrobatics','skill.animal':'Animal Handling','skill.arcana':'Arcana','skill.athletics':'Athletics','skill.deception':'Deception','skill.history':'History','skill.insight':'Insight','skill.intimidation':'Intimidation','skill.investigation':'Investigation','skill.medicine':'Medicine','skill.nature':'Nature','skill.perception':'Perception','skill.performance':'Performance','skill.persuasion':'Persuasion','skill.religion':'Religion','skill.sleight':'Sleight of Hand','skill.stealth':'Stealth','skill.survival':'Survival',
  'footer.text':'Hero Forge · Made for adventures, not paperwork.'
} satisfies Record<MessageKey,string>;
