export const ptBR = {
  'app.brand':'Forja de Heróis','app.tagline':'Personagens memoráveis. Prontos antes da primeira iniciativa.','nav.presets':'Personagens prontos','nav.characters':'Meus personagens','nav.language':'Idioma',
  'home.eyebrow':'FERRAMENTA PARA ONE-SHOTS','home.title':'Sua próxima lenda começa agora.','home.create':'Criar personagem','home.choosePreset':'Escolher personagem pronto','home.auto':'Cálculos automáticos','home.local':'Salvo no dispositivo','home.pdf':'PDF pronto para imprimir','home.quick':'CRIAÇÃO RÁPIDA','home.quickTitle':'Pronto para jogar em poucos minutos','home.quickBody':'Escolha um arquétipo de nível 5, dê um nome e ajuste apenas o que quiser.','home.quickAction':'Começar criação rápida →','home.available':'10 arquétipos disponíveis',
  'common.level':'Nível','common.remove':'Remover','common.add':'Adicionar','common.edit':'Editar','common.duplicate':'Duplicar','common.delete':'Excluir','common.back':'← Voltar','common.continue':'Continuar →','common.save':'Salvar personagem','common.downloadPdf':'Baixar PDF','common.cancel':'Cancelar','common.yes':'Sim','common.no':'Não','common.auto':'Auto','common.custom':'Custom',
  'steps.identity':'Identidade','steps.classSpecies':'Classe & espécie','steps.abilities':'Atributos','steps.skills':'Perícias','steps.combat':'Combate & itens','steps.spells':'Magias & notas','steps.portrait':'Retrato','steps.review':'Revisão',
  'editor.new':'Novo aventureiro','editor.creation':'CRIAÇÃO DE PERSONAGEM','editor.step':'ETAPA {current} DE {total}','form.characterName':'Nome do personagem','form.characterPlaceholder':'Como seu herói é conhecido?','form.playerName':'Nome do jogador','form.required':'Campo obrigatório','form.class':'Classe','form.subclass':'Subclasse / caminho','form.subclassPlaceholder':'Escolha conforme sua mesa','form.species':'Espécie','form.armorClass':'Classe de armadura','form.hp':'PV','form.hpAverage':'Média automática','form.hpManual':'Valor manual','form.manualHp':'PV manual','form.notes':'Anotações',
  'pointBuy.rules':'Regras','pointBuy.used':'Usados','pointBuy.available':'Disponíveis','pointBuy.remaining':'Restantes','pointBuy.final':'Atributos finais','pointBuy.finalHelp':'Inclua bônus de espécie, background, talentos e ASI. Estes valores não alteram o Point Buy.','validation.pointBuy':'Configuração inválida: ajuste os atributos comprados ao limite de pontos.','validation.total':'Total de pontos inválido.','validation.integerLimits':'Limites devem ser inteiros.','validation.range':'O mínimo não pode superar o máximo.','validation.level':'O limite de nível deve estar entre 1 e 20.','validation.cost':'Custo inválido para o atributo {score}.',
  'custom.total':'Total de pontos','custom.minimum':'Atributo mínimo','custom.maximum':'Atributo máximo','custom.levelLimit':'Limite de nível','custom.costTable':'Tabela de custos',
  'attack.title':'Ataques','attack.name':'Nome','attack.damageDie':'Dano','attack.ability':'Atributo','attack.proficient':'Proficiente','attack.attackBonus':'Bônus de ataque','attack.damageBonus':'Bônus de dano','attack.new':'Nova arma','attack.add':'Adicionar ataque','equipment.title':'Equipamentos','equipment.new':'Novo item','spell.title':'Magias','spell.name':'Nome','spell.level':'Nível','spell.new':'Nova magia','spell.add':'Adicionar magia','skill.expertise':'Expertise',
  'portrait.title':'Retrato do personagem','portrait.help':'PNG, JPG ou WEBP. A imagem também aparecerá no PDF.','portrait.choose':'Escolher imagem','sheet.title':'FICHA DE AVENTUREIRO','sheet.unnamed':'Herói sem nome','sheet.hp':'PV','sheet.ac':'CA','sheet.initiative':'INIC.','sheet.proficiency':'PROF.','sheet.saves':'Salvaguardas','sheet.skills':'Perícias','sheet.attacks':'Ataques','sheet.equipment':'Equipamento','sheet.spells':'Magias','sheet.notes':'Anotações','sheet.features':'Recursos','sheet.attack':'ataque','sheet.damage':'dano',
  'library.eyebrow':'BIBLIOTECA LOCAL','library.help':'Seus heróis ficam salvos somente neste dispositivo.','library.new':'Novo personagem','library.empty':'Sua companhia ainda está vazia','library.emptyHelp':'Crie um herói ou comece por um arquétipo pronto.','library.viewPresets':'Ver personagens prontos','library.confirmDelete':'Excluir este personagem?','library.copy':'(cópia)','preset.eyebrow':'CRIAÇÃO RÁPIDA','preset.title':'Escolha seu arquétipo','preset.help':'Todos começam no nível 5 e podem ser completamente personalizados.','preset.use':'Usar e personalizar','preset.ready':'Um {role} de nível 5, pronto para entrar em cena.','preset.featureArchetype':'Arquétipo de nível 5','preset.featureResources':'Ataques e recursos de classe','preset.notes':'Ajuste escolhas de subclasse e recursos conforme os livros permitidos pela mesa.',
  'role.tank':'Guerreiro tanque','role.barbarian':'Bárbaro de força','role.rogue':'Ladino furtivo','role.wizard':'Mago ofensivo','role.cleric':'Clérigo suporte','role.paladin':'Paladino guardião','role.ranger':'Ranger batedora','role.bard':'Bardo versátil','role.monk':'Monge ágil','role.warlock':'Bruxo ocultista',
  'ability.strength':'Força','ability.dexterity':'Destreza','ability.constitution':'Constituição','ability.intelligence':'Inteligência','ability.wisdom':'Sabedoria','ability.charisma':'Carisma',
  'class.fighter':'Guerreiro','class.barbarian':'Bárbaro','class.rogue':'Ladino','class.wizard':'Mago','class.cleric':'Clérigo','class.paladin':'Paladino','class.ranger':'Ranger','class.bard':'Bardo','class.monk':'Monge','class.warlock':'Bruxo',
  'species.human':'Humano','species.elf':'Elfo','species.dwarf':'Anão','species.halfling':'Halfling','species.tiefling':'Tiefling','species.dragonborn':'Draconato',
  'skill.acrobatics':'Acrobacia','skill.animal':'Adestrar Animais','skill.arcana':'Arcanismo','skill.athletics':'Atletismo','skill.deception':'Enganação','skill.history':'História','skill.insight':'Intuição','skill.intimidation':'Intimidação','skill.investigation':'Investigação','skill.medicine':'Medicina','skill.nature':'Natureza','skill.perception':'Percepção','skill.performance':'Atuação','skill.persuasion':'Persuasão','skill.religion':'Religião','skill.sleight':'Prestidigitação','skill.stealth':'Furtividade','skill.survival':'Sobrevivência',
  'footer.text':'Forja de Heróis · Feito para aventuras, não para burocracia.'
} as const;
